fixtures:
  repositories:
    "augeasproviders_core":
      repo: "git://github.com/hercules-team/augeasproviders.git"
      ref: "2c3f228bbfd2a18c83c63ec9553764a4c572f5e6"
  symlinks:
    augeasproviders_shellvar: "#{source_dir}"
