fixtures:
  repositories:
    "augeasproviders_core":
      repo: "git://github.com/hercules-team/augeasproviders.git"
      ref: "691ab78f72acfe5f14d894400f34505f779a45b7"
  symlinks:
    augeasproviders_shellvar: "#{source_dir}"
